{% set name = "requests-kerberos" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 437512e424413d8113181d696e56694ffa4259eb9a5fc4e803926963864eaf4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0.0
  run:
    - __unix  # [unix]
    - __win   # [win]
    - cryptography >=1.3
    - pyspnego
    - pykrb5 >=0.3.0  # [not win]
    - python-gssapi >=1.6.0  # [not win]
    - python >=3.8
    - requests >=1.1.0

test:
  requires:
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests/
  commands:
    - python -m pip check
    - python -m pip show requests-kerberos
    - python -m pytest -ra -v tests/

about:
  home: https://github.com/requests/requests-kerberos
  dev_url: https://github.com/requests/requests-kerberos
  doc_url: https://pypi.org/project/requests-kerberos/
  license: ISC
  license_family: MIT
  license_file: LICENSE
  summary: A Kerberos authentication handler for python-requests
  description: |
    Requests is an HTTP library, written in Python, for human beings.
    This library adds optional Kerberos/GSSAPI authentication support
    and supports mutual authentication.

extra:
  recipe-maintainers:
    - duncanmmacleod
